### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by zwei-beiner** [dfm/tinygp#156]
I've been running inference codes with GPs, which require instantiating new GPs in a loop. However, I've noticed that the usual way of doing this steadily consumes an increasing amount of memory as new GP objects are created. I suspect that the GaussianProcess objects are not deallocated from memory.
Below is a minimal example. If I monitor the system memory taken up by this process while running the example, I can see that it increases and eventually goes beyond multiple gigabytes.
Is there a fix for this?

```[python]
import numpy as np

import tinygp
from tinygp import noise
import jax.numpy as jnp
import jax

jax.config.update("jax_enable_x64", True)

t_train = np.linspace(0, 10, 100)
y_train = np.sin(t_train) + np.random.normal(0, 0.1, len(t_train))
y_train_err = np.full_like(t_train, 0.1)

def build_gp(p):
    kernel = (p[0] ** 2) * tinygp.kernels.ExpSquared(p[1])
    return tinygp.GaussianProcess(kernel, t_train, noise=noise.Diagonal(y_train_err ** 2), mean=lambda x: jnp.float64(0.))

nDims = 2

@jax.jit
def lnlikelihood(theta):
    gp = build_gp(theta)
    logl = gp.log_probability(y_train)
    return logl


t_test = np.array([0.])
samples = np.zeros(int(1e6))
_, *subkeys = jax.random.split(key=jax.random.PRNGKey(1), num=len(samples))
for i, rand in enumerate(np.random.rand(len(samples), nDims)):
    print(i)
    # Create gp object
    _, gp = build_gp(rand).condition(y_train, t_test)
    # Do something with the gp object
    samples[i] = gp.sample(subkeys[i])
    # gp object not needed anymore

print(np.mean(samples), np.std(samples))

```

**Comment by dfm** [comment]
I think the general approach would be to split the `.condition` and whatever else you're doing with the conditioned gp object into a separate function that you can `jit`. I'm happy to give more specific tips if that isn't sufficient and you want to post more details.

**Comment by zwei-beiner** [comment]
@dfm Is this what you mean? 
```
import numpy as np

import tinygp
from tinygp import noise
import jax.numpy as jnp
import jax

jax.config.update("jax_enable_x64", True)

t_train = np.linspace(0, 10, 100)
y_train = np.sin(t_train) + np.random.normal(0, 0.1, len(t_train))
y_train_err = np.full_like(t_train, 0.1)

def build_gp(p):
    kernel = (p[0] ** 2) * tinygp.kernels.ExpSquared(p[1])
    return tinygp.GaussianProcess(kernel, t_train, noise=noise.Diagonal(y_train_err ** 2), mean=lambda x: jnp.float64(0.))

nDims = 2

@jax.jit
def take_sample(theta):
    _, gp = build_gp(theta).condition(y_train, t_test)
    return gp.sample(subkeys[i])

t_test = np.array([0.])
samples = np.zeros(int(1e6))
_, *subkeys = jax.random.split(key=jax.random.PRNGKey(1), num=len(samples))
for i, rand in enumerate(np.random.rand(len(samples), nDims)):
    print(i)
    # Do something with the gp object
    samples[i] = take_sample(rand)
    # gp object not needed anymore

print(np.mean(samples), np.std(samples))
```

**Comment by dfm** [comment]
Yes! Something like that (although, you'll probably want to take the key as input to `take_sample` because right now I don't think it'll do what you want!).

**Comment by zwei-beiner** [comment]
Ok, thanks! It does seem to use a constant amount of memory now. 

I wanted to ask why this works: Since `GaussianProcess` is not a jax type, how does jax remove the overhead of instantiating the `GaussianProcess` object (as claimed [here](https://tinygp.readthedocs.io/en/stable/tutorials/intro.html): "jax can optimize out all the Python overhead introduced by instantiating the kernel and gp objects"). I presume that jax does not jit recursively because if I add `jax.jit` directly in front of the `build_gp` function, I get an error.

**Comment by dfm** [comment]
There are a few reasons why the `jit` works/helps here. The details get a bit into the guts of JAX, but I'm happy to give a brief overview:

1. When you `jit` the `take_sample` function, it turns out that `GaussianProcess` objects are _only instantiated the first time the function is called_, and in that case, they aren't instantiated with any associated data so there is very little overhead. When you call the `jit`ted function, it only ever executes pre-compiled XLA machine code that doesn't know anything about the Python objects.

2. The second reason is specific to the `condition` method. When you call condition outside of a `jit` context, it actually does a lot of unnecessary computations and allocates a bunch of unneeded memory. This is OK in practice, because the preferred use is within a `jit`ted function where all of this gets optimized out and never executed.

It's true that you can't `jit` the `build_gp` function because (as you discovered) a `tinygp.GaussianProcess` cannot be interpreted by JAX. This behavior could be changed, but there are some reasons that are beyond the scope of this discussion for why that would be hard and perhaps introduce other issues.

Hope this helps!

**Comment by zwei-beiner** [comment]
@dfm If I am not using `jax.jit`, is there a way around this memory leak?

**Comment by dfm** [comment]
Not that I'm aware of (and it would make everything much slower!!) but there may be hacks in specific scenerios. But generally always better to use `jit`

**Comment by zwei-beiner** [comment]
Ok, thanks a lot, that helps!
