### ISSUE TITLE
`sample()` not working

### ISSUE THREAD

**Issue by sblunt** [dfm/tinygp#48]
Totally possible I'm doing something silly, but I can't get the `sample()` functionality to work. Here's a basic example. Plotting the functional form of the kernel works fine.

```
import matplotlib.pyplot as plt
import numpy as np
import tinygp
import jax

random = np.random.default_rng(546)

log_exp = np.log(5.)
kernel = tinygp.kernels.ExpSquared(log_exp)
t = np.sort(random.uniform(0, 10, 1000))
mygp = tinygp.GaussianProcess(
    kernel, t
)

fig = plt.subplots()
plt.plot(t, mygp.kernel(t, t)[0])
plt.savefig('kernel_test.png')

y = mygp.sample(jax.random.PRNGKey(123))
print(y)
```

(y returns all nans)

**Comment by dfm** [comment]
This happens when the matrix is not numerically positive definite, which is often true if you don't include any `diag` term. Our implementation is slightly stricter than `multivariate_normal` because we re-use the Cholesky factorization of the covariance matrix. Therefore, to get your example to work, you can replace:

```diff
mygp = tinygp.GaussianProcess(
-     kernel, t
+     kernel, t, diag=1e-5
)
```

for some small number on the diagonal. We could also consider implementing a more robust sample function using the SVD (like numpy does), but then we wouldn't be able to re-use the factorization (making it slow) and it would give us a false sense of security (that GP model also has `nan` as its logp :D).

**Comment by dfm** [comment]
It's worth noting that you can set smaller values on the diagonal after [enabling double precision](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#double-64bit-precision).

**Comment by sblunt** [comment]
Awesome!! Thanks Dan! :)
